### ISSUE TITLE
Full width pane

### ISSUE THREAD

**Issue by Tychodewaard** [DNNCommunity/DNNCommunityTheme#10]
## Is your feature request related to a problem?
**Please describe.**
The design has a big blue header. So either, we need an adjustment of the headerpane or a full with pane added
Below the blue header there is a content slider with a light brown background. So either there is another full width pane with that colour or the header has no colour and we create classes.

![Home-Desktop20190521-2](https://user-images.githubusercontent.com/9091997/58636410-88c6c280-82f0-11e9-9cf7-ae5aa7b326fc.png)

**Comment by nvisionative** [comment]
@Tychodewaard this was actually resolved via PR #21 - I'll go ahead and close this issue out.
