### ISSUE TITLE
Expanded menu

### ISSUE THREAD

**Issue by Tychodewaard** [DNNCommunity/DNNCommunityTheme#11]
## Is your feature request related to a problem?
**Please describe.**
According to the design, the menu shows sublevel in a wide 80% transparency background color.
![Home-Desktop-menu-expandeed20190521](https://user-images.githubusercontent.com/9091997/58636673-215d4280-82f1-11e9-9dc5-70ef6b9b9a3b.png)

**Comment by nvisionative** [comment]
@Tychodewaard this design does not account for 3rd level nav items (which we do already have on the site).  I will give this some thought and see what I can come up with.

**Comment by nvisionative** [comment]
@Tychodewaard I believe we now only have 2 levels of page hierarchy, so we are good there now.  However, I am of the opinion at this point that we do not have enough 2nd level pages to warrant a mega menu.  Implementing a mega menu for 0 - 6 subpages seems overkill.  If you are okay with this, let's put this issue on hold until the site grows a bit more.

**Comment by Tychodewaard** [comment]
Ok, we’ll first put our energy on other stuff
