### ISSUE TITLE
Containers - Cant use containers from other themes

### ISSUE THREAD

**Issue by D0rk80** [DNNCommunity/DNNCommunityTheme#115]
## Describe the bug
DNN PLATFORM
v. 09.10.00 (0)
.NET FRAMEWORK
4.8
DNNCommunityTheme_1.1.1_install.zip

Love the theme thanks for the upload!!!

## To Reproduce
Apply containers theme to a html or any other module and the container doesn't show. The only thing that changes is the text size . Apply another theme for me it I change it to the default DNN 9.10 theme default and the containers show up. You can go anywhere on the site to see the none container shipped with this theme. I need to be able to change the containers theme pls.

http://support.vigilant1.com/Tester123

**Comment by david-poindexter** [comment]
@D0rk80 thank you for posting the issue.  This theme was developed for a specific DNN community website.  If you need/want to us the theme in a different fashion than intended, you are most welcome to fork the repo and do your own custom implementation.  Typically speaking, we don't recommend mixing the use of containers between themes though.  😉

**Comment by D0rk80** [comment]
yeah ive been with dnn since the early days and just never had the issue. just kind of been able to select from module settings what container theme.

I wouldnt mind paying for the fix.

**Comment by david-poindexter** [comment]
Awesome.  I am not 100% clear on what you think needs fixing on this theme.  For the purposes it was built, it is working perfectly.  If you are trying to use it as a basis for another project, great!  You can totally add/edit/remove containers for that implementation.  

If it is another theme's container that you are trying to use within this theme, then the source for the other theme's container comes into play.  And it may or may not be compatible with this theme.  For instance, this theme uses Bootstrap 4.  If that theme's container(s) leverage a different version of Bootstrap, or another CSS Framework, or pure CSS that conflicts with this theme, then you will most likely get undesirable results.  For these reasons, and more, it is best to just add/edit the containers in your forked version of this theme to meet the specific needs of your implementation.

If you need some help with that fork, feel free to reach out to me and we'll see what we can do.  As it relates to this project, we won't be making any changes here that are not necessary for the project in which this theme is used.  I hope that makes sense.

**Comment by D0rk80** [comment]
sorry to clarify
fresh dnn install - started with dnn 9.06 upgraded to 9.10
fresh theme install
when you apply the theme to the site and apply the module to the page > go into module settings > page settings > module container I should be able to select a container and it be displayed but for some reason its not when using this theme.

**Comment by david-poindexter** [comment]
Understood @D0rk80 - thanks for the clarification.  Again, you are more than welcome to "fork" this entire project into a repo on your own GitHub account and make any additions, edits, subtractions you need for your purposes.  I would recommend making those on a separate `branch` though just so you can "sync" things later with this repo should we make any changes/improvements in the future.

If that is all "Greek" to you, no worries.  I am happy to work with you on this project, but we will need to get the project into another GitHub repo to make changes from there.  Go ahead and send me a communication via [HERE](https://www.nvisionative.com/contact) and I'll respond as soon as possible with next step recommendations.

**Comment by D0rk80** [comment]
Thanks man I understand. Ive taken it as far as I can go would need to pay for help from you please.
