### ISSUE TITLE
Nunito font

### ISSUE THREAD

**Issue by Tychodewaard** [DNNCommunity/DNNCommunityTheme#12]
## Is your feature request related to a problem?
**Please describe.**
Avenir is a licensed font. Nunito is an open source alternative.:

Nunito: https://fonts.google.com/specimen/Nunito 
<style> 
@import url('https://fonts.googleapis.com/css?family=Nunito&display=swap'); 
</style> 
 
font-family: 'Nunito', sans-serif;

**Comment by nvisionative** [comment]
@Tychodewaard I am working now to replace the Open Sans font with the Nunito font.  I will have a PR submitted shortly.
