### ISSUE TITLE
Add Blog Template to the Theme

### ISSUE THREAD

**Issue by hismightiness** [DNNCommunity/DNNCommunityTheme#30]
The core [blog module](https://github.com/DNNCommunity/Dnn.Blog) allows you to insert, store, and load its template through the theme.  We should package and maintain the blog theme in this way.

The template files should go into a folder named `Template` per the code:

https://github.com/DNNCommunity/DNN.Blog/blob/62a3121669026306e71542804f6ba58ea8030282/Controls/ViewSettings.ascx.vb#L103

**Comment by nvisionative** [comment]
Okay, according to the [Blog module manual](https://github.com/DNNCommunity/DNN.Blog/blob/development/_Documentation/Manual.md#templating), all blog template files can be placed in **[SkinDirectory]/Templates/Blog**.  We are going to need to define exactly what we want to include/style.  In looking into the settings on the community site, it appears someone has already created a **Community2019** template.  Can someone with FTP access send me a ZIP of that folder?

**Comment by hismightiness** [comment]
[Community2019.zip](https://github.com/DNNCommunity/DNNCommunityTheme/files/3269713/Community2019.zip)
Here you go, sir! :)

**Comment by nvisionative** [comment]
Thanks @hismightiness - I’ll try to get this incorporated as soon as possible.

**Comment by hismightiness** [comment]
👀 

😄

**Comment by hismightiness** [comment]
I was planning on resolving #35 and #36 myself once you resolve this one.  😁
