### ISSUE TITLE
Blog JS Errors when sharing

### ISSUE THREAD

**Issue by hismightiness** [DNNCommunity/DNNCommunityTheme#35]
## Describe the bug
This will need to be looked into after the blog template is properly added to the source via issue #30 .

When you attempt to like a comment in a blog post, JS errors are thrown.  This is likely needing to be resolved in the template and it could require that the website Google Analytics script is changed/updated.

## To Reproduce
1. Go to any [blog post](https://dnncommunity.org/blogs/Post/330/Welcome-to-the-New-DNN-Community-Website).  If there isn't at least one comment, add one.
2. Click on the like icon to like it.

## Expected behavior
The comment appears that it was liked and no errors are thrown in the console.

**Comment by nvisionative** [comment]
@hismightiness this is now ready to be looked into.  I have assigned the issue to you and labeled it as a bug.  Thanks for your patience awaiting the PR for #30.
