### ISSUE TITLE
Change the icons on the blog listing view

### ISSUE THREAD

**Issue by hismightiness** [DNNCommunity/DNNCommunityTheme#36]
## Describe the bug
The blog listing view either is not using icons for the comments and views, or using the wrong icon set.  This is a simple change that will need to be made after the issue #30 is resolved.

https://dnncommunity.org/blogs

**Comment by nvisionative** [comment]
@hismightiness this one is now ready to be looked into.  Thank you for your patience in awaiting a PR for #30.
