### ISSUE TITLE
Blog Template: Add Max-Width to the CSS

### ISSUE THREAD

**Issue by hismightiness** [DNNCommunity/DNNCommunityTheme#37]
## Describe the bug
When images are uploaded of a certain width, they can become bigger than their allocated with in desktop scenarios.  To be completed once issue #30 is resolved.

![image](https://user-images.githubusercontent.com/938023/59191936-c53abf80-8b35-11e9-992c-cd6c84179d1a.png)

Desktop Max-Width should be 730px.

**Comment by nvisionative** [comment]
The example you cite has width and height (and other inline CSS) hardcoded.  Instead of that, the Bootstrap 4 class **img-fluid** should be applied to the image.  Let me know if you are good with this issue being closed.

**Comment by hismightiness** [comment]
D'oh!  I normally remove those as part of my workflow.  🤦‍♂ 

Whoops!
