### ISSUE TITLE
Mobile Login / Password Reset and other responsive styling issues

### ISSUE THREAD

**Issue by parasdaryanani** [DNNCommunity/DNNCommunityTheme#38]
## Describe the bug
The login and password reset pages need to be optimised for mobile view. I will attach screenshots and a proposed solution for the issues.

## Expected behavior
- [ ] The form input fields should be of consistent width
- [ ] The form should be visible on the page on its own
- [ ] The page should (ideally) only allow zoom-in and not zoom-out (viewport minimum-scale=1.0)

## Screenshots

(Screenshot below shows that the page can be zoomed out. This is due to the cookie consent alert. Putting that aside, the login form is not visible within the viewport without zooming out).
![Screenshot_2019-06-10-12-39-34-847_com android chrome](https://user-images.githubusercontent.com/5025488/59193757-ad3b5e00-8b7e-11e9-8034-72e6d4854e8b.png)

(Screenshot below shows the form input fields are not of the same width).
![Screenshot_2019-06-10-12-28-05-146_com android browser](https://user-images.githubusercontent.com/5025488/59193758-ad3b5e00-8b7e-11e9-957f-d742ac52330d.png)

**Comment by Timo-Breumelhof** [comment]
yes

**Comment by Timo-Breumelhof** [comment]
:-)

**Comment by david-poindexter** [comment]
@parasdaryanani this has been partially addressed in the latest release of the theme (1.1.0).  There is still a minor issue to resolve regarding the `Register` and `Reset Password` buttons, but at least it is not doing what it was before.

I think we can close this issue now and address the remaining needs via more granular issues.  Thanks!

**Comment by david-poindexter** [comment]
Current look and feel:

![image](https://user-images.githubusercontent.com/4568451/99896291-318f7d00-2c5d-11eb-8e97-083dcb10e3bb.png)
