### ISSUE TITLE
Homepage Forums feed displays unparsed HTML

### ISSUE THREAD

**Issue by parasdaryanani** [DNNCommunity/DNNCommunityTheme#39]
**EDIT:** I'm not sure if this bug belongs to the theme itself; please let me know if I need to report it somewhere else.

## Describe the bug
On the homepage below the image from DNN Connect, the forums activity feed shows recent posts and comments. Among these, plain HTML is visible on the frontend which suggests that that there needs to be some parsing involved to render the HTML, rather than display it on the page. See screenshot below.

## Screenshots
![html](https://user-images.githubusercontent.com/5025488/59194575-5f742500-8b81-11e9-8191-7a333782f0dc.png)

**Comment by Timo-Breumelhof** [comment]
This is a bug in the blog module IMO https://github.com/DNNCommunity/DNN.Blog/issues/157
