### ISSUE TITLE
"Sticky" Menu

### ISSUE THREAD

**Issue by CBPSC** [DNNCommunity/DNNCommunityTheme#45]
## Is your feature request related to a problem?
**Please describe.**
Can we make the main menu stick to the top of the page when the user scrolls down?

## Describe the solution you'd like
Currently the main menu is lost when the user scrolls down the page. Can we update the nav menu to be fixed upon scroll? I've done this previously on a site using jQuery ([http://wehuntsc.com/HOME](http://wehuntsc.com/HOME)) but that is likely not the desired implementation here.

**Comment by nvisionative** [comment]
Great suggestion @CBPSC - this will be super simple.  All we need is a class added to the header.  I'll get this in the queue ASAP.
