### ISSUE TITLE
Hovered submenu is same color as header

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNNCommunityTheme#55]
## Describe the bug
When hovering the submenu items, they the the blue color which is exactly the same as the header pane so it looks like there is just a menu gap.

## To Reproduce
Hover in menus while seing the blue header

## Expected behavior
We should have something to surround the menu, like a border or a shadow so that it does not blend in with the underlying color.

## Screenshots
![image](https://user-images.githubusercontent.com/6371568/60121031-2f677d00-9750-11e9-8eea-008b9a5be80d.png)

**Comment by david-poindexter** [comment]
@valadas thank you for pointing this out.  This is a great recommendation.  It was not originally an issue, but we updated the color scheme to minimize the use of the red brand color and this is a bit of a side effect from those changes.  😄👍
