### ISSUE TITLE
Add Border-Radius to Blog Author Images (make the picture round)

### ISSUE THREAD

**Issue by CBPSC** [DNNCommunity/DNNCommunityTheme#64]
## Is your feature request related to a problem?
**Please describe.**
Most profile pics on the net are circular in nature. The blog module is currently display author pics as square and I think it would look better if it were rounded. This could be done by applying a class with the property of "border-radius:50%;" (or something similar to that) to the image.

## Describe the solution you'd like
An image with rounded edges instead of hard, square edges

## Additional context
See image on right column --> https://dnncommunity.org/blogs/Post/1109/2019-DNN-MVP-Nominations-are-Open

**Comment by david-poindexter** [comment]
@CBPSC my apologies on the delayed response.  I have this slated for the 1.0.8 release of the theme.
