### ISSUE TITLE
Add PopUp Skin

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/DNNCommunityTheme#65]
## Is your feature request related to a problem?
**Please describe.**
On DNNcommunity.org you can see that DNN loads the full skin in some places in the PB.
I just realized that this is because the skin does not contain a popup skin.
AFAIK DNN should use the default one, but apparently there it doesn't.
I tried this locally with one of my own skins and with a popup skin it looks much better..

## Describe the solution you'd like
Add a popupskin (popUpSkin.ascx, case sensitive)

## Describe alternatives you've considered
Do nothing.

**Comment by david-poindexter** [comment]
@Timo-Breumelhof thanks for reporting this issue.  Do you plan to submit a pull request?  If so, I'll assign this to the 1.0.8 release milestone.  Thanks!

**Comment by Timo-Breumelhof** [comment]
@david-poindexter maybe stale bot should not mark issues with a pull request or is that intentional?

**Comment by valadas** [comment]
I don't think dependabot is aware if an issue has a pull request for it or not... What I have done in other projects is I made a "pull request submitted" tag and added that tag to the dependabot config to ignore them.

**Comment by david-poindexter** [comment]
@Timo-Breumelhof my apologies, I should have already processed your PR, but I keep dismissing it in my list due to the nondescript title.  🤣 I'll get to it as soon as possible.
