### ISSUE TITLE
Messaging reply box enhancement

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/DNNCommunityTheme#66]
## Is your feature request related to a problem?
**Please describe.**
When replying to messages, the textarea is very small compared to the font size, I would prefer to make it bigger

## Describe the solution you'd like
Add this css:

.DnnModule-Messaging-Details textarea#replyMessage{
    height:15em;  
    width:100%;
}

## Describe alternatives you've considered
Ignore :-)

## Additional context

![image](https://user-images.githubusercontent.com/8999382/60527792-3fa0ce80-9cf3-11e9-8141-1e05c418be33.png)

![image](https://user-images.githubusercontent.com/8999382/60527823-52b39e80-9cf3-11e9-94ed-7e88598776c6.png)

**Comment by david-poindexter** [comment]
Thanks for reporting this enhancement @Timo-Breumelhof.  Do you plan to submit a pull request?  If not, I'll go ahead and include this in the 1.0.8 release.  Thanks.

**Comment by Timo-Breumelhof** [comment]
Thanks, I don't have much time ATM.. :-(
