### ISSUE TITLE
Change Body color to #000000 for readability

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/DNNCommunityTheme#98]
## Describe the bug
The color of the text is dark grey.
Due to the fact that the font-weight is also 200, that's not optimal for readability.

## To Reproduce
Visit the site and look at the readability of the text on for instance a blog post

## Expected behavior
Have a bigger contrastbetween text and background

## Screenshots
![image](https://user-images.githubusercontent.com/8999382/99089760-ff7f7a80-25cd-11eb-97e4-24667566e90f.png)

After change to #000000

![image](https://user-images.githubusercontent.com/8999382/99089881-26d64780-25ce-11eb-96d8-d42354af51c1.png)

**Comment by Timo-Breumelhof** [comment]
@david-poindexter thank you for taking care of this :-)

**Comment by david-poindexter** [comment]
You are most welcome @Timo-Breumelhof 🎉
